seeds: [7, 19, 42, 73, 101, 256, 512, 1024, 2048]

data:
  data_name: Citeseer
  data_class: Planetoid
  batch_size: 64
  num_workers: 4

model:
  name: gcn
  hidden_dim: 16
  dropout: 0.5
  early_stopping: 10

train:
  epochs: 200
  lr: 0.01
  weight_decay: 0.0005
  device: cuda